include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    lines_longer_than_80_chars: false
