name: cloudpayments_api
description: This package allows implementing payment acceptance into mobile, web, desktop apps and works as an extension to the CloudPayments API

version: 1.0.4

homepage: https://github.com/glin94/cloudpayments_api

repository: https://github.com/glin94/cloudpayments_api

issue_tracker: https://github.com/glin94/cloudpayments_api/issues

topics:
  - payments
  - cloudpayments

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.5
  test: ^1.23.1
  very_good_analysis: ^7.0.0
